In [11]:
### first version, demo
bi_ADMM=function(X, nu1, nu2, lambda_1, lambda_2, v, z, gamma_1, gamma_2, niter = 1000, imax = 0.1){
  A = X
  n = dim(X)[1]; p = dim(X)[2]
  eplison_p = L_num(p); eplison_n = L_num(n)
  fx=rep(0,niter)
  A_old = A; v_old = v; z_old = z; 
  lambda_1_old = lambda_1; lambda_2_old = lambda_2
  for(iter in 2:niter){
    if(iter %% 10 ==0){print(paste('iter',iter))}
    # update A 
    A = update_A(X, nu1, nu2, lambda_1, lambda_2, v, z)
    
    # update V and Z
    vz = update_vz(X, A, lambda_1, lambda_2, gamma_1, gamma_2, nu1, nu2)
    v = vz[[1]]
    z = vz[[2]]

    # update lambda_1 and lambda_2 
    lambda = update_lambda(X, A, nu1, nu2,v, z)
    lambda1 = lambda[[1]]
    lambda2 = lambda[[2]]

    print(paste('A:',round(sum(abs(A - A_old)),2),
                '  v:',round(sum(abs(v - v_old)),2) ,
                '  z:',round(sum(abs(z - z_old)),2) ,
                '  l1:',round(sum(abs(lambda1 - lambda_1_old)),2),
                '  l2:',round(sum(abs(lambda2 - lambda_2_old)),2)))
    
    term1=term2=term3=0
    for(i in 1:n){
      term1 = term1 + t(X[i,] - A[i,]) %*% (X[i,] - A[i,])
    }
    
    for(i in  1:dim(eplison_n)[1]){
      l1=eplison_n[i,'l1']
      l2=eplison_n[i,'l2']
      term2 = term2 + t(v[,i] + 1/nu1 * lambda1[,i]- A[l1,] + A[l2,]) %*% (v[,i] - A[l1,] + A[l2,])
    }
    
    for(i in  1:dim(eplison_p)[1]){
      l1=eplison_p[i,'l1']
      l2=eplison_p[i,'l2']
      term3 = term3 + t(z[,i] + 1/nu2 * lambda2[,i]- A[,l1] + A[,l2]) %*% (z[,i] - A[,l1] + A[,l2])
    }
    
    fx[iter] = 0.5 * term1 + 0.5* nu1 * term2 + 0.5*nu2*term3
    
    if(fx[iter] < fx[iter - 1]){print('small')}
    
    # whether coverage
    if(sum(abs(A - A_old)) < e & 
       sum(abs(v - v_old)) < e & 
       sum(abs(z - z_old)) < e & 
       sum(abs(lambda1 - lambda_1_old)) < e & 
       sum(abs(lambda2 - lambda_2_old)) < e){
      return(list(A = A, v = v, z = z, lambad_1 = lambda1, lambad_2 = lambda2, niter = iter-1))
      break
    }
    A_old = A; v_old = v; z_old = z; 
    lambda_1_old = lambda1; lambda_2_old = lambda2
  }
  if(iter == 1000){
    print(paste('not converge within',iter, 'times'))
    return(list(A = A, v = v, z = z, lambad_1 = lambda1, lambad_2 = lambda2, niter = iter-1))
  }
}

In [14]:
# prepare data
X = matrix(1:12,4,3)
A = X

nu1=1; nu2=1; gamma_1 = 0.5; gamma_2 = 0

n=dim(X)[1]; p=dim(X)[2]
eplison_p=L_num(p)
eplison_n=L_num(n)

lambda_1 = matrix(1,p,dim(eplison_n)[1])
lambda_2 = matrix(1,n,dim(eplison_p)[1])

v = matrix(1,p,dim(eplison_n)[1])
z = matrix(1,n,dim(eplison_p)[1])

e = 0.1

In [15]:
bi_ADMM(X, nu1, nu2, lambda_1, lambda_2, v, z, gamma_1, gamma_2, niter = 1000, imax = 0.1)

[1] "A: 38.4   v: 16.86   z: 24   l1: 16.86   l2: 12"
[1] "A: 9.33   v: 9.32   z: 16   l1: 1.28   l2: 0"
[1] "small"
[1] "A: 6.97   v: 7.09   z: 12   l1: 0.27   l2: 0"
[1] "small"
[1] "A: 5.27   v: 5.84   z: 9   l1: 0.28   l2: 0"
[1] "small"
[1] "A: 4.01   v: 4.83   z: 6.75   l1: 0.14   l2: 0"
[1] "small"
[1] "A: 3.05   v: 3.94   z: 5.06   l1: 0.08   l2: 0"
[1] "small"
[1] "A: 2.32   v: 3.2   z: 3.8   l1: 0.06   l2: 0"
[1] "small"
[1] "A: 1.76   v: 2.59   z: 2.85   l1: 0.04   l2: 0"
[1] "small"
[1] "iter 10"
[1] "A: 1.34   v: 2.09   z: 2.14   l1: 0.03   l2: 0"
[1] "small"
[1] "A: 1.02   v: 1.69   z: 1.6   l1: 0.02   l2: 0"
[1] "small"
[1] "A: 0.78   v: 1.36   z: 1.2   l1: 0.02   l2: 0"
[1] "small"
[1] "A: 0.59   v: 1.1   z: 0.9   l1: 0.01   l2: 0"
[1] "small"
[1] "A: 0.46   v: 0.89   z: 0.68   l1: 0.01   l2: 0"
[1] "small"
[1] "A: 0.36   v: 0.71   z: 0.51   l1: 0.01   l2: 0"
[1] "small"
[1] "A: 0.29   v: 0.58   z: 0.38   l1: 0.01   l2: 0"
[1] "small"
[1] "A: 0.22   v: 0.46   z: 0.29   

$A
         [,1]     [,2]      [,3]
[1,] 1.103995 5.098643  9.093292
[2,] 1.953375 5.948024  9.942672
[3,] 3.057328 7.051976 11.046625
[4,] 3.906708 7.901357 11.896005

$v
         [,1]      [,2]      [,3]     [,4]      [,5]     [,6]
[1,] -1.79472 -2.953333 -2.103952 -3.77613 -2.953333 -1.79472
[2,] -1.79472 -2.953333 -2.103952 -3.77613 -2.953333 -1.79472
[3,] -1.79472 -2.953333 -2.103952 -3.77613 -2.953333 -1.79472

$z
          [,1]      [,2]      [,3]
[1,] -4.994649 -8.989297 -4.994649
[2,] -4.994649 -8.989297 -4.994649
[3,] -4.994649 -8.989297 -4.994649
[4,] -4.994649 -8.989297 -4.994649

$lambad_1
          [,1]          [,2]          [,3]       [,4]          [,5]      [,6]
[1,] 0.0546607  0.000000e+00  0.000000e+00 0.02658324 -4.440892e-16 0.0546607
[2,] 0.0546607 -8.881784e-16 -8.881784e-16 0.02658324  0.000000e+00 0.0546607
[3,] 0.0546607  0.000000e+00  0.000000e+00 0.02658324  0.000000e+00 0.0546607

$lambad_2
              [,1]          [,2] [,3]
[1,]  0.000000e+00  0.000000e+00    0
[2,]  0.000000e+00 -1.776357e-15    0
[3,] -8.881784e-16  0.000000e+00    0
[4,]  0.000000e+00  0.000000e+00    0

$niter
[1] 24

### a larger

In [16]:
simu_4 = function(n, true_p, p, k, mu, sigma, seed = NULL){
  
  if(! is.null(seed) ){ set.seed(seed)  }
  n_p <- true_p / 2
  n_k <- n / k
  clust.ind <- rep(1:k, each = n_k)
  clust.mat <- rbind( c(rep( mu, n_p), rep(-mu, n_p)), 
                      c(rep(-mu, n_p), rep(-mu, n_p)),
                      c(rep(-mu, n_p), rep( mu, n_p)),
                      c(rep( mu, n_p), rep( mu, n_p))
  )
  
  X = matrix(0,n,p)
  for(i in 1:n){
    mu_mean <- c( clust.mat[clust.ind[i],], rep(0, p - true_p) )
    X[i,] <- rnorm(p, mu_mean,rep(sigma,p))
  }
  
  list(X = X, label = clust.ind, features = c(rep(TRUE, true_p), rep(FALSE, p - true_p)))
  
}
X =simu_4(400,2,100,1,1,1)
X = X$X

In [17]:
A = X

nu1=1; nu2=1; gamma_1 = 0.5; gamma_2 = 0

n=dim(X)[1]; p=dim(X)[2]
eplison_p=L_num(p)
eplison_n=L_num(n)

lambda_1 = matrix(1,p,dim(eplison_n)[1])
lambda_2 = matrix(1,n,dim(eplison_p)[1])

v = matrix(1,p,dim(eplison_n)[1])
z = matrix(1,n,dim(eplison_p)[1])

In [20]:
t1 = Sys.time()
  A = X
  n = dim(X)[1]; p = dim(X)[2]
  eplison_p = L_num(p); eplison_n = L_num(n)

  A_old = A; v_old = v; z_old = z; 
  lambda_1_old = lambda_1; lambda_2_old = lambda_2

  for(iter in 1:10){
    print(paste('iter',iter))
    # update A 
      print('A')
    A = update_A(X, nu1, nu2, lambda_1, lambda_2, v, z)
    
    # update V and Z
      print('vz')
    vz = update_vz(X, A, lambda_1, lambda_2, gamma_1, gamma_2, nu1, nu2)
    v = vz[[1]]
    z = vz[[2]]

    # update lambda_1 and lambda_2 
      print('lambda')
    lambda = update_lambda(X, A, nu1, nu2,v, z)
    lambda1 = lambda[[1]]
    lambda2 = lambda[[2]]

    print(paste('A:',round(sum(abs(A - A_old)),2),
                '  v:',round(sum(abs(v - v_old)),2) ,
                '  z:',round(sum(abs(z - z_old)),2) ,
                '  l1:',round(sum(abs(lambda1 - lambda_1_old)),2),
                '  l2:',round(sum(abs(lambda2 - lambda_2_old)),2)))
    
    # whether coverage
    if(sum(abs(A - A_old)) < e & 
       sum(abs(v - v_old)) < e & 
       sum(abs(z - z_old)) < e & 
       sum(abs(lambda1 - lambda_1_old)) < e & 
       sum(abs(lambda2 - lambda_2_old)) < e){
      #return(list(A = A, v = v, z = z, lambad_1 = lambda1, lambad_2 = lambda2, niter = iter-1))
      break
    }
    A_old = A; v_old = v; z_old = z; 
    lambda_1_old = lambda1; lambda_2_old = lambda2
  }
t2 = Sys.time()

[1] "iter 1"
[1] "A"
[1] "vz"
[1] "lambda"
[1] "A: 62001.1   v: 7960054.02   z: 1960398.96   l1: 7979975.96   l2: 1980000"
[1] "iter 2"
[1] "A"
[1] "vz"
[1] "lambda"
[1] "A: 407.59   v: 31939.11   z: 26805.99   l1: 9.25   l2: 0"
[1] "iter 3"
[1] "A"
[1] "vz"
[1] "lambda"
[1] "A: 403.75   v: 31860.81   z: 26545.97   l1: 9.13   l2: 0"
[1] "iter 4"
[1] "A"
[1] "vz"
[1] "lambda"
[1] "A: 399.94   v: 31782.25   z: 26288.55   l1: 9.11   l2: 0"
[1] "iter 5"
[1] "A"
[1] "vz"
[1] "lambda"
[1] "A: 396.17   v: 31704.47   z: 26033.71   l1: 9.17   l2: 0"
[1] "iter 6"
[1] "A"
[1] "vz"
[1] "lambda"
[1] "A: 392.44   v: 31626.72   z: 25781.43   l1: 9.11   l2: 0"
[1] "iter 7"
[1] "A"
[1] "vz"
[1] "lambda"
[1] "A: 388.74   v: 31549.84   z: 25531.68   l1: 8.86   l2: 0"
[1] "iter 8"
[1] "A"
[1] "vz"
[1] "lambda"
[1] "A: 385.09   v: 31473.76   z: 25284.44   l1: 8.94   l2: 0"
[1] "iter 9"
[1] "A"
[1] "vz"
[1] "lambda"
[1] "A: 381.47   v: 31397.63   z: 25039.7   l1: 8.95   l2: 0"
[1] "iter 10"
[1] "A"
[1] "vz"

In [21]:
t2-t1

Time difference of 20.90849 mins

In [1]:
#The function to generate $l = (l_1, l_2)$, where $l_1 < l_2$
tri2vec <- function(i,j,n) {
  return(n*(i-1) - i*(i-1)/2 + j -i)
}

In [2]:
L_num=function(n){
  library(tidyr)
  L=matrix(0,n,n)
  for(i in 1:n){
    for(j in 1:n){
      L[i,j] = paste(i,',',j)
    }
  }
  l=c(L[upper.tri(L)])
  ll=data.frame(l)
  
  LL=ll %>% separate(l,c('l1','l2'),sep=',')
  LL=data.frame(l1=as.numeric(LL[,'l1']),l2=as.numeric(LL[,'l2']))
  return(LL)
}

In [5]:
### 2. sylvester equation
sylvester = function(A, B, C, eps = 0.0001){
  
  library(MASS)
  library(Matrix)
  
  A1 = Schur(A)
  Q1 = A1$Q; R1 = A1$T
  
  A2 = Schur(B)
  Q2 = A2$Q; R2 = A2$T 
  C = t(Q1) %*% C %*% Q2
  
  Rsq = R1 * R1
  I = diag(dim(A)[1])
  
  k = 1
  n = dim(R2)[1]
  
  while(k < n + 1){
    if(k < n){
      if(abs(R2[k+1, k]) < eps){
        left = R1 + R2[k,k] * I
        right = C[,k]
        temp = matrix(0, dim(X)[1],1)
        if(k == 1){
          temp = temp
        }else{
          for(i in 1:(k-1)){
            temp = temp + X[,i] * R2[i,k]
          }
        }
        temp = matrix(temp, dim(C)[1],1)
        X[,k] = ginv(left) %*% (right - temp)
       # mytry = myTryCatch(solve(left))
        #if(is.null(mytry$error) == 0){er = c(er,tt)}
        k = k+1
      }else{
        r11 = R2[k,k]; r12 = R2[k, k+1]; r21 = R2[k+1, k]; r22 = R2[k+1, k+1]
        temp2 = matrix(0, dim(X)[1],1);temp3=matrix(0, dim(X)[1],1)
        if(k == 1){
          temp2 = temp2
          temp3 = temp3
        }else{
          for(i in 1:(k-1)){
            temp2 = temp2 + X[,i] * R2[i,k]
            temp3 = temp3 + X[,i] * R2[i,k+1]}
        }
        temp2 = matrix(temp2, dim(X)[1],1)
        temp3 = matrix(temp3, dim(X)[1],1)
        b1 = C[,k] - temp2 
        b2 = C[,k+1] - temp3
        b1_prime = R1 %*% b1 + r22 * b1 - r21 * b2
        b2_prime = R1 %*% b2 + r11 * b2 - r12 * b1
        b_prime = matrix(0, dim(X)[1],2)
        b_prime[,1] = b1_prime; b_prime[,2] = b2_prime
        X[,k:(k+1)] = ginv(R1 %*% R1 + (r11 + r22) * R1 +
                             (r11*r22 - r12*r21) * I) %*% b_prime 
        k = k+2
      }
    }else{
      if(abs(R2[1, k]) > eps){
        left = R1 + R2[k,k] * I
        right = C[,k]
        temp = matrix(0, dim(X)[1],1)
        if(k == 1){
          temp = temp
        }else{
          for(i in 1:(k-1)){
            temp = temp + X[,i] * R2[i,k]
          }
        }
        temp = matrix(temp, dim(C)[1],1)
        X[,k] = ginv(left) %*% (right - temp)
        k = k+1
      }else{
        R22 = R2
        R22 = cbind(R2, rep(0,dim(R2)[1]))
        R22 = rbind(R22,rep(0,dim(R2)[1]+1))
        r11 = R22[k,k]; r12 = R22[k, k+1]; r21 = R22[k+1, k]; r22 = R22[k+1, k+1]
        temp2 = matrix(0, dim(X)[1],1);temp3=matrix(0, dim(X)[1],1)
        for(i in 1:(k-1)){
          temp2 = temp2 + X[,i] * R22[i,k]
          temp3 = temp3 + X[,i] * R22[i,k+1]}
        temp2 = matrix(temp2, dim(X)[1],1)
        temp3 = matrix(temp3, dim(X)[1],1)
        b1 = C[,k] - temp2 
        b2 = - temp3
        b1_prime = R1 %*% b1 + r22 * b1 - r21 * b2
        b2_prime = R1 %*% b2 + r11 * b2 - r12 * b1
        b_prime = matrix(0, dim(X)[1],2)
        b_prime[,1] = b1_prime; b_prime[,2] = b2_prime
        GOD = ginv(R1 %*% R1 + (r11 + r22) * R1 +
                     (r11*r22 - r12*r21) * I) %*% b_prime 
        X[,k] = GOD[,1]
        k = k+2
      }
    }
  }
  return(Q1 %*% X %*% t(Q2))
}


In [6]:
### 3. update A
update_A = function(X, nu1, nu2, lambda_1, lambda_2, v, z){
  library(MASS)
  library(Matrix)
  n=dim(X)[1]; p=dim(X)[2]
  eplison_n=L_num(n)
  eplison_p=L_num(p)
  
  En=matrix(0,n,n)
  Ep=matrix(0,p,p)
  
  # calculate \sum_{l \in \epsilon_1}(e_{l1} - e_{l_2})(e_{l1} - e_{l_2})^T, which is En
  for(i in 1:dim(eplison_n)[1]){
    l1=eplison_n[i,'l1']
    l2=eplison_n[i,'l2']
    el1=matrix(rep(0,n),n,1)
    el2=matrix(rep(0,n),n,1)
    el1[l1,1]=1;el2[l2,1]=1
    En=En+(el1-el2) %*% t(el1-el2)
  }
  
  # calculate \sum_{k \in \epsilon_2} (e_{k1} - e_{k_2})(e_{k1} - e_{k_2})^T, which is Ep
  for(i in 1:dim(eplison_p)[1]){
    l1=eplison_p[i,'l1']
    l2=eplison_p[i,'l2']
    el1=matrix(rep(0,p),p,1)
    el2=matrix(rep(0,p),p,1)
    el1[l1,1]=1;el2[l2,1]=1
    Ep=Ep+(el1-el2) %*% t(el1-el2)
  }
  
  M = diag(1,n,n) + nu1 * En
  
  N = nu2 * Ep
  t3 = Sys.time()
  # C2 is the second part of C, which is \sum_{l \in \epsilon_1} (e_{l1} - e_{l_2})(\lambda_{l1} + \nu_1 v_l)^T 
  C2 = matrix(0,n,p) 
  for(i in 1:dim(eplison_n)[1]){
    l1=eplison_n[i,'l1']
    l2=eplison_n[i,'l2']
    el1=matrix(rep(0,n),n,1)
    el2=matrix(rep(0,n),n,1)
    el1[l1,1]=1;el2[l2,1]=1
    C2 = C2 + (el1-el2) %*% t(lambda_1[,i]+ nu1 * v[,i])
  }
  t4= Sys.time()
  # C3 is the third part of C, which is \sum_{k \in \epsilon_2} (\lambda_{k2} + \nu_2 z_k)(e_{k1} - e_{k_2})^T
  C3 = matrix(0,n,p)
  for(i in 1:dim(eplison_p)[1]){
    l1=eplison_p[i,'l1']
    l2=eplison_p[i,'l2']
    el1=matrix(rep(0,p),p,1)
    el2=matrix(rep(0,p),p,1)
    el1[l1,1]=1;el2[l2,1]=1
    C3 = C3+(lambda_2[,i] + nu2 * z[,i]) %*% t(el1-el2)
  }
  
  C = X +  C2 + C3  
  
  A = sylvester(M,t(N),C)
  
  return(A)
}

In [7]:
prox = function(v,sigma){
  return(max(1-sigma/sum(t(v) %*% v),0) * v)
}
v = 1:5
prox(v, 0.1)

[1] 0.9981818 1.9963636 2.9945455 3.9927273 4.9909091

In [8]:
dist_weight <- function(X, phi){
  dist_X <- as.numeric(dist(X))
  return(exp(- phi * dist_X^2))
}
knn_weights <- function(w,k,n) {
  i <- 1
  neighbors <- tri2vec(i,(i+1):n,n)
  keep <- neighbors[sort(w[neighbors],decreasing=TRUE,index.return=TRUE)$ix[1:k]]
  for (i in 2:(n-1)) {
    group_A <- tri2vec(i,(i+1):n,n)
    group_B <- tri2vec(1:(i-1),i,n)
    neighbors <- c(group_A,group_B)
    knn <- neighbors[sort(w[neighbors],decreasing=TRUE,index.return=TRUE)$ix[1:k]]
    keep <- union(knn,keep)
  }
  i <- n
  neighbors <- tri2vec(1:(i-1),i,n)
  knn <- neighbors[sort(w[neighbors],decreasing=TRUE,index.return=TRUE)$ix[1:k]]
  keep <- union(knn,keep)
  w[-keep] <- 0
  return(w)
}

In [9]:
update_vz = function(X, A, lambda_1, lambda_2, gamma_1, gamma_2, nu1, nu2){
  
  n=dim(X)[1]; p=dim(X)[2]
  eplison_n=L_num(n)
  eplison_p=L_num(p)
 
  w <- dist_weight(X / sqrt(p),phi = 0.5)
  w_l <- knn_weights(w,k = 1,n)

  u = dist_weight(t(X) / sqrt(n),phi = 0.5)
  u_k <- knn_weights(u,k = 1,p)
  
  for(i in 1:dim(eplison_n)[1]){
    l1=eplison_n[i,'l1']
    l2=eplison_n[i,'l2']
    a_l1 = A[l1,]; a_l2 = A[l2,]
    v_temp = a_l1 - a_l2 - 1/nu1 * lambda_1[,i]
    sigma_1l = gamma_1 * w_l[i]/nu1
    v[,i] = prox(v_temp,sigma_1l)
  }
  
  for(i in 1:dim(eplison_p)[1]){
    l1=eplison_p[i,'l1']
    l2=eplison_p[i,'l2']
    a_l1 = A[,l1]; a_l2 = A[,l2]
    v_temp = a_l1 - a_l2 - 1/nu2 * lambda_2[,i]
    #u_k = exp(-0.5 * (t(X[,l1] - X[,l2]) %*% (X[,l1] - X[,l2])))
    sigma_2k = gamma_2 * u_k[i]/nu2
    z[,i] = prox(v_temp,sigma_2k)
  }
  
  return(list(v = v, z = z))
}

In [10]:
### 5. update lambda
update_lambda=function(X, A, nu1, nu2,v, z){
  n = dim(X)[1]; p = dim(X)[2]
  eplison_p = L_num(p)
  eplison_n = L_num(n)
  # update lambda 1
  for(i in 1:dim(eplison_n)[1]){
    l1=eplison_n[i,'l1']
    l2=eplison_n[i,'l2']
    a_l1 = matrix(A[l1,],p,1)
    a_l2 = matrix(A[l2,],p,1)
    lambda_1[,i] = lambda_1[,i] + nu1 * (v[,i] - a_l1 + a_l2)
  } 
  # update lambda 2
  for(i in 1:dim(eplison_p)[1]){
    l1=eplison_p[i,'l1']
    l2=eplison_p[i,'l2']
    a_k1 = matrix(A[,l1],n,1)
    a_k2 = matrix(A[,l2],n,1)
    lambda_2[,i] = lambda_2[,i] + nu2 * (z[,i] - a_k1 + a_k2)
  }
  return(lambda=list(lambda_1,lambda_2))
}